# Copied from pdoc's own recommendations
# see https://pdoc.dev/docs/pdoc.html#deploying-to-github-pages
#
name: Doc on Github Pages

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
      - name: Install dependencies
        shell: bash -l {0}
        run: |
            conda install gdal libgdal-kea
            pip install pdoc
            pip install -e .
      - name: Build docs
        shell: bash -l {0}
        run: python docs/buildDoc.py

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
